### PR TITLE
Add CI to ZeroSync

### PR DESCRIPTION
**Pull request by Jrigada**
# Add CI to run tests

This workflow runs the utreexo bridge node and the project tests

### CODE REVIEW

**Comment by lucidLuckylee** [comment]
Very nice work. One thing that comes to my mind is an issue we ran into with the standard protostar version and the starknet step limit of 1 (or now maybe 2) million steps. To run larger tests we had to build starknet-devnet and protostar using a modified version of cairo-lang with a higher step limit.
However, I am not sure what the best solution out there is to install a modified version of protostar while keeping it up to date.

**Comment by RobinLinus** [comment]
> limit of 1 (or now maybe 2) million steps.

should we really always run those expensive tests every time someone makes a commit? 
Can we parametrize our tests somehow to have like a "light" and a "full" mode or so?

**Comment by lucidLuckylee** [comment]
We could think of a naming scheme and have protostar only target specific test files:

´´´
test_light_function
test_full_function

protostar test target */**/test_full*.cairo
´´´

We currently only reach the step
limit when we test whole blocks so it is definitely not an urgent problem. We can keep a note around that in case you see "OUT_OF_RESOURCES" your tests are reaching the step limit.

**Comment by lucidLuckylee** [comment]
We could think of a naming scheme and have protostar only target specific test files:

´´´
test_light_function
test_full_function

protostar test target */**/test_full*.cairo
´´´

We currently only reach the step
limit when we test whole blocks so it is definitely not an urgent problem. We can keep a note around that in case you see "OUT_OF_RESOURCES" your tests are reaching the step limit.

**Comment by RobinLinus** [comment]
I'd say let's just keep uncommenting the slow tests for now and activate them manually when needed.

**Pull request merged**
